name: Build and Push Docker Image

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Get the short commit hash
    - name: Get short commit hash
      id: vars
      run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    # Log in to GitHub Docker Registry
    - name: Log in to GitHub Docker Registry
      run: echo "$" | docker login ghcr.io -u $ --password-stdin

    # Build the Docker image
    - name: Build Docker image
      run: |
        REPO_OWNER=$(echo "$" | tr '[:upper:]' '[:lower:]')
        REPO_NAME=$(echo "$" | tr '[:upper:]' '[:lower:]')
        IMAGE_TAG=$([[ "$" == "push" && "$" =~ ^refs/tags/ ]] && echo "$" || echo "$")
        docker build . --file Dockerfile --tag ghcr.io/$REPO_OWNER/$REPO_NAME:${IMAGE_TAG}
        docker tag ghcr.io/$REPO_OWNER/$REPO_NAME:${IMAGE_TAG} ghcr.io/$REPO_OWNER/$REPO_NAME:latest

    # Push the Docker image to GitHub Container Registry
    - name: Push Docker image
      run: |
        REPO_OWNER=$(echo "$" | tr '[:upper:]' '[:lower:]')
        REPO_NAME=$(echo "$" | tr '[:upper:]' '[:lower:]')
        IMAGE_TAG=$([[ "$" == "push" && "$" =~ ^refs/tags/ ]] && echo "$" || echo "$")
        docker push ghcr.io/$REPO_OWNER/$REPO_NAME:${IMAGE_TAG}
        docker push ghcr.io/$REPO_OWNER/$REPO_NAME:latest
